name: Build Android for store

on:
  workflow_dispatch: {}

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: path/to/your/project/Library
          key: Library-BeatThat-Android
          restore-keys: |
            Library-BeatThat-
            Library-

      - uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: Android
          androidAppBundle: 'true'

      - uses: actions/upload-artifact@v2
        with:
          name: Build-Android
          path: build/Android
      