name: build
on:
  workflow_dispatch: {}

jobs:
  buildAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Android APK
        run: |
          # Placeholder command for building APK
          echo "Building Android APK..."
          mkdir -p build/Android
          touch build/Android/example.apk  # Create a placeholder APK file

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Build-Android
          path: build/Android